apiVersion: v1
kind: Ingress
metadata:
  name: {{ include "request-data.name" . }}
  namespace: {{ .Values.namespace }}
  labels:
    app: {{ include "request-data.name" . }}
  annotations:
    kubernetes.io/ingress.class: "alb"
    alb.ingress.kubernetes.io/scheme: "internet-facing"
    alb.ingress.kubernetes.io/target-type: "ip"
spec:
  host: {{ .Values.service.host }}
  http:
    paths:
      - pathType: Prefix
        path: /
        backend:
          service:
            name: {{ include "request-data.fullname" . }}
            port:
              number: 80
