apiVersion: argoproj.io/v1alpha1
kind: Application
metadata:
  name: req-data-app
spec:
  project: default
  source:
    repoURL: 'https://github.com/martinkaburu/request-data.git'
    path: helm/
    targetRevision: main
    helm:
      parameters:
        - name: image.tag
          generate: true
  destination:
    server: 'https://kubernetes.default.svc'
    namespace: req-data
  syncPolicy:
    automated:
      prune: true
  syncOptions:
    - PreSync='GIT_SHA=$(git rev-parse HEAD) && sed -i "s/PLACEHOLDER/$GIT_SHA/g" values.yaml'
