project: default
source:
  repoURL: 'https://github.com/martinkaburu/request-data.git'
  path: helm/
  targetRevision: HEAD
  helm:
    valueFiles:
      - values.yaml
destination:
  server: 'https://kubernetes.default.svc'
  namespace: req-data
syncPolicy:
  automated:
    prune: true
  syncOptions:
    - Replace=true
    - Validate=false
    - CreateNamespace=true
    - ApplyOutOfSyncOnly=true
  retry:
    limit: 2
    backoff:
      duration: 5s
      factor: 2
      maxDuration: 3m0s