fullnameOverride: request-data
replicaCount: 1
image:
  repository: martinkaburu/request-data
  tag: 21c946d18189b594f9076489805f667c42bf750d
  pullPolicy: Always
service:
  type: LoadBalancer
  port: 80
