fullnameOverride: request-data
replicaCount: 1
namespace: req-data
image:
  repository: martinkaburu/request-data
  tag: c662d16d6416987f047a1db0abebe4169f621b6d
  pullPolicy: Always
service:
  type: LoadBalancer
  port: 80
ingress:
  ingressClassName: alb
  host: echo.martinkaburu.me
