fullnameOverride: request-data
replicaCount: 1
namespace: req-data
image:
  repository: martinkaburu/request-data
  tag: aacb7d776ace6ac89a068ee643305e6cbe7fc88a
  pullPolicy: Always
  port: 5000
service:
  type: LoadBalancer
  port: 80
ingress:
  ingressClassName: alb
  host: echo.martinkaburu.me
