fullnameOverride: request-data
replicaCount: 1
namespace: req-data
image:
  repository: martinkaburu/request-data
  tag: 890fb24b43d41d7ac7bcf1f0d07b5666a11821e5
  pullPolicy: Always
  port: 5000
service:
  type: LoadBalancer
  port: 80
ingress:
  ingressClassName: alb
  host: echo.martinkaburu.me
