fullnameOverride: request-data
replicaCount: 1
namespace: req-data
image:
  repository: martinkaburu/request-data
  tag: 1814a081f7e01b1bfe7756d8891cfa210bc90400
  pullPolicy: Always
service:
  type: LoadBalancer
  host: echo.martinkaburu.me
  port: 80
