fullnameOverride: request-data
replicaCount: 1
namespace: req-data
image:
  repository: martinkaburu/request-data
  tag: 97196c26a6db7a77bb0cf7943d85166743832475
  pullPolicy: Always
  port: 5000
service:
  type: LoadBalancer
  port: 80
ingress:
  ingressClassName: alb
  host: echo.martinkaburu.me
