fullnameOverride: request-data
replicaCount: 1
namespace: req-data
image:
  repository: martinkaburu/request-data
  tag: b9169ede3d2242d78d4a132753e94425d4992b8c
  pullPolicy: Always
  port: 5000
service:
  type: LoadBalancer
  port: 80
ingress:
  ingressClassName: alb
  host: echo.martinkaburu.me
