fullnameOverride: request-data
replicaCount: 1
namespace: req-data
image:
  repository: martinkaburu/request-data
  tag: 3fde19a307aa9b82d5eaa81185dbfa31adc8595f
  pullPolicy: Always
service:
  type: LoadBalancer
  port: 80
ingress:
  ingressClassName: alb
  host: echo.martinkaburu.me

