fullnameOverride: request-data
replicaCount: 1
namespace: req-data
image:
  repository: martinkaburu/request-data
  tag: 350f374512e5f7da384961b9e4e76e44c368d21b
  pullPolicy: Always
service:
  type: LoadBalancer
  host: echo.martinkaburu.me
  port: 80
