fullnameOverride: request-data
replicaCount: 1
namespace: req-data
image:
  repository: martinkaburu/request-data
  tag: 8e1f27d1fa87d904400689cdaf4f239938e0e6ca
  pullPolicy: Always
service:
  type: LoadBalancer
  port: 8080
ingress:
  ingressClassName: alb
  host: echo.martinkaburu.me
