fullnameOverride: request-data
replicaCount: 1
namespace: req-data
image:
  repository: martinkaburu/request-data
  tag: 040e383970f036db39c7c27d90b834f772f3351d
  pullPolicy: Always
service:
  type: LoadBalancer
  host: echo.martinkaburu.me
  port: 80
