fullnameOverride: request-data
replicaCount: 1
namespace: req-data
image:
  repository: martinkaburu/request-data
  tag: 46bd6ecf93314f96b6df25a14cba1ac6069e9b24
  pullPolicy: Always
service:
  type: LoadBalancer
  host: echo.martinkaburu.me
  port: 80
