fullnameOverride: request-data
replicaCount: 1
namespace: req-data
image:
  repository: martinkaburu/request-data
  tag: 6b20a85a646ed1d44ccb9314f19bace2364e33a8
  pullPolicy: Always
service:
  type: LoadBalancer
  host: echo.martinkaburu.me
  port: 80
