name: Build and Push Docker Image

on:
  push:
    branches:
      - main

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - name: Check if user is allowed to trigger build
        if: github.actor != 'ReqDataGithubBot'
        run: |
      - name: Checkout repository
        uses: actions/checkout@v2

      - name: Log in to Docker Hub
        uses: docker/login-action@v2
        with:
          username: ${{ secrets.DOCKER_USERNAME }}
          password: ${{ secrets.DOCKER_PASSWORD }}

      - name: Build Docker image
        run: docker build -t ${{ secrets.DOCKER_USERNAME }}/request-data:${{ github.sha }} .

      - name: Push Docker image to Docker Hub
        run: docker push ${{ secrets.DOCKER_USERNAME }}/request-data:${{ github.sha }}

      - name: Update values.yaml
        run: |
          yq eval ".image.tag = \"${{ github.sha }}\"" -i helm/values.yaml

      - name: Commit changes
        run: |
          git config --global user.email "martinkaburu.m@gmail.com"
          git config --global user.name "ReqDataGithubBot"
          git add helm/values.yaml
          git commit -m "Update image tag to latest commit"
          git push origin main
